(defun check (func)
  (let ((ret func))
    (format t "return: ~a~%" ret)))

(format t "eq~%")
(check (eq 'a 'a))
(check (eq 100 100))
(check (eq 100 100.0))
(check (eq #\a #\a))
(check (eq #\a #\A))
(check (eq "aa" "aa"))
(check (eq (list 1 2) (list 1 2)))

(format t "eql~%")
(check (eql 'a 'a))
(check (eql 100 100))
(check (eql 100 100.0))
(check (eql #\a #\a))
(check (eql #\a #\A))
(check (eql "aa" "aa"))
(check (eql (list 1 2) (list 1 2)))


(format t "equal~%")
(check (equal 'a 'a))
(check (equal 100 100))
(check (equal 100 100.0))
(check (equal #\a #\a))
(check (equal #\a #\A))
(check (equal "aa" "aa"))
(check (equal (list 1 2) (list 1 2)))

(format t "equalp~%")
(check (equalp 'a 'a))
(check (equalp 100 100))
(check (equalp 100 100.0))
(check (equalp #\a #\A))
(check (equalp "aa" "aa"))
(check (equalp (list 1 2) (list 1 2)))